name: Build and Package

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: 
      - "**"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build and Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BalatroInstanceManager
        path: bin/Release/net8.0-windows/win-x64/publish/*.exe